name: Self-Hosted Runner Test
on: 
  push:
    branches:
    - master
jobs:
  Runner-1:
    runs-on: [ self-hosted, Ubuntu-22 ]
    steps:
    - uses: actions/checkout@v2
    - name: Server User
      run: whoami
    - name: Server OS-Information
      run: cat /etc/os-release
    - name: Server Public Address
      run: curl ifconfig.me
  Runner-2:
    runs-on: [ self-hosted, AmazonLinux-2 ]
    steps:
    - uses: actions/checkout@v2
    - name: Server User
      run: whoami
    - name: Server OS-Information
      run: cat /etc/os-release
    - name: Server Public Address
      run: curl ifconfig.me