name: Self-Hosted Runner Test

on: 
  push:
    branches:
    - master

jobs:
  Runner-1:
    runs-on: [ self-hosted, Ubuntu-22 ]
    steps:
    - uses: actions/checkout@v2

    - name: Server Details
      run: |
        whoami
        cat /etc/os-release